### ISSUE TITLE
2 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by dvlop** [phrutis/Fialka#24]
exe file from x64 directory on virustotal.com show "2 security vendors and no sandboxes flagged this file as malicious"
<img width="822" alt="image" src="https://user-images.githubusercontent.com/1873578/158277340-a6040b63-a5ec-4077-9c5e-5b570feaefab.png">

**Comment by phrutis** [comment]
What could be harmful? There is an open source code.
